[package]
name    = "cargo-ohrs"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.4.8",features = ["derive"]}

[[bin]]
name = 'cargo-ohrs'
path = 'src/main.rs'
