# Action name
name: Simple Test Action

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
  push

# Jobs section
jobs:
  simple-test:
    runs-on: ubuntu-latest
    container:
      image: southorange/ohos-base:v4
    steps:
      - uses: actions/checkout@v4

      - name: install
        # GitHub action can't run with root user, so rust's toolchain need to re-install.
        run:  cargo install ohrs && cd examples/hello && ohrs build
