# Action name
name: Simple Test Action

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
  push

# Jobs section
jobs:
  simple-test:
    runs-on: ubuntu-latest
    container:
      image: southorange/ohos-base:v4
    steps:
      - uses: actions/checkout@v4

      - name: install
        run:  export PATH="${HOME}/.cargo/bin:${PATH}" && rustup default nightly && rustup component add rust-src && cargo install ohrs && echo $PATH && cd examples/hello && ohrs build
